baseURL = "https://derekroyse.github.io/HugoResume/"
languageCode = "en-us"
title = "Derek Royse"
theme = "lodi"
googleAnalytics = "UA-XXXXXXXX-Y"
publishDir = "docs"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Derek Royse, Web Applications Developer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "derekroyse@gmail.com"
    linkedin = "https://www.linkedin.com/in/DerekRoyse"    
    github = "DerekRoyse"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Derek, a Full Stack Web Developer and Cybersecurity Enthusiast."
    hero_right = [
    	"**Full stack web developer with more than 5 years of experience developing and maintaining mid to large-scale web applications.**", 
    	"Oversaw dev department and worked hand-in-hand with multiple emergency management organizations during the COVID pandemic to rapidly develop and deploy new features and apps to respond to their evolving needs.",
    	"Adept at handling all stages of development and ensuring customer satisfaction and prompt results. Experienced working remotely with clients and team members.",
    	"I'm also passionate about cybersecurity and I am currently CompTIA Security+ and Cybersecurity Analyst (CySA)+ certified."
    ]
    resume = "Derek Royse - Resume.pdf"

[params.experience]
    enable = true
    title = "Experience"

[params.education]
    enable = false
    title = "Education"  

[params.process]
    enable = true
    title = "Skills" 

[params.case_studies]
    enable = true
    title = "Portfolio"
    subtitle = "Recent Work"  

[params.footer]
    enable = true
